services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=jobless
      - MYSQL_USER=webscraper
      - MYSQL_PASSWORD=webscraper